Rename host-side build scripts to bake (all.sh), php/bake (mk.sh),     multi/bake (multi.sh) & tools/bake (tools/mk.sh) Dispatch Dockerfiles to php/, tools/ & multi/ and remove docker/ Move all file COPY commands to the $...COPY variables in Dockerfiles Move pkgs/ in top directory to php/ Move all run-side files to run/ subdirs of php/, tools/ & multi/ Make php/run/build find the latest PHP version from the PHP source filename Add (docker) run script to debian/*/multi/ Add debian/*/mkre files to define PHP versions to make by default Limit PHP release and build numbers to 2 digits Change all CMD commands to exec syntax Update README.md

diff --git a/bake b/bake
--- a/bake
+++ b/bake
@@ -1,19 +1,23 @@
 #!/bin/sh
 #
-#	all.sh - Build all latest PHP distribs, tools and multi
+#	bake - Bake all latest PHP distribs, tools and multi
 #
 PHPSITE='fr.php.net'
 
 Prg=`basename $0`
 Dir=`dirname $0`
+IniPwd=$PWD
 #Do=:	# Remove comment to not actually execute commands (for debug)
 
 LF='
 '
 
+Path() { realpath --relative-to=$IniPwd $1; }
+test "$Dir" || Dir=`dirname \`realpath $0\``
+expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
 test "$Dir" = '.' || cd "$Dir"
 test -d debian || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }
-test -d docker || { echo "$Prg: missing 'docker' directory." >&2; exit 1; }
+test -d php    || { echo "$Prg: missing 'php' directory." >&2;    exit 1; }
 
 #
 #   Parse args (rm or mk so far)
@@ -117,6 +121,7 @@ do
 		echo 1 >php/$Maj/$v/BUILD_NUM
 	    fi
 	    Bld=`cat php/$Maj/$v/BUILD_NUM`
+	    eval "MUL$d=\"\$MUL$d\$v-\$Bld \""
 	    Dir=debian/$d/dist/$v-$Bld
 	    if [ -d $Dir ]; then
 		echo "$v is already built for $n"
@@ -124,8 +129,7 @@ do
 	    fi
 	    echo "Building $v for $n in $Dir"
 	    $Do mkdir -p $Dir
-	    $Do ./mk.sh $v $d | sed -u 's/$//' | $Do tee $Dir/mk.out | sed -u 's/$//'
-	    eval "MUL$d=\"\$MUL$d\$v-\$Bld \""
+	    $Do php/bake $v $d | sed -u 's/$//' | $Do tee $Dir/mk.out | sed -u 's/$//'
 	done
 
 	Dir=debian/$d/dist/tools
@@ -134,7 +138,7 @@ do
 	else
 	    echo "Building tools for $n"
 	    $Do mkdir -p $Dir
-	    $Do tools/mk.sh $d | sed -u 's/$//' | $Do tee $Dir/mk.out | sed -u 's/$//'
+	    $Do tools/bake $d | sed -u 's/$//' | $Do tee $Dir/mk.out | sed -u 's/$//'
 	fi
     fi
 done
@@ -161,6 +165,6 @@ if [ "$mk" ]; then
     elif [ "$Mul" ]; then
 	echo "Building and running multi for $n with $Mul"
 	test -d $Dir || $Do mkdir $Dir
-	$Do ./multi.sh $Mul | sed -u 's/$//' | $Do tee $Dir/mk.out | sed -u 's/$//'
+	$Do multi/bake $Mul | sed -u 's/$//' | $Do tee $Dir/mk.out | sed -u 's/$//'
     fi
 fi
diff --git a/multi/bake b/multi/bake
--- a/multi/bake
+++ b/multi/bake
@@ -2,27 +2,38 @@
 #
 #	Test the use of multiple PHP versions
 #
-#	Usage:	./multi.sh <PHP-dist-dir> [<PHP-dist-dir> ...] [<Debian-version>]
+#	Usage:	[multi|.]/bake <PHP-dist-dir> [<PHP-dist-dir> ...] [<Debian-version>]
 #
-Prg=`basename $0`
+Prg=multi/`basename $0`
 Dir=`dirname $0`
+IniPwd=$PWD
+TopDir=../
+DebTop=${TopDir}debian
+PhpTop=${TopDir}php
+TlsTop=${TopDir}tools
+MulTop=
+
+Path() { realpath --relative-to=$IniPwd $1; }
+test "$Dir" || Dir=`dirname \`realpath $0\``
+expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
+test "$Dir" = '.' || cd "$Dir"
+#   Script's CWD is where it is located, but all messages assume PWD is top-level
+test -d $DebTop || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }
+test -d $PhpTop || { echo "$Prg: missing 'php' directory." >&2;  exit 1; }
+test -d $TlsTop || { echo "$Prg: missing 'tools' directory." >&2;  exit 1; }
+
+DefDeb=`ls $DebTop | sort -n | tail -1`	# Default = latest
 Base='epi-php'
 Arch='amd64'
 LF='
 '
-
-test "$Dir" = '.' || cd "$Dir"
-test -d debian || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }
-test -d docker || { echo "$Prg: missing 'docker' directory." >&2; exit 1; }
-DefDeb=`ls debian | sort -n | tail -1`	# Default = latest
-
 #
 #    Parse args
 #
 for arg in "$@"
 do
-    d=`expr "$arg" : '\([5-9]\.[0-9]\.[0-9][0-9]*-[0-9][0-9]*\)$'`
-    v=`expr "$arg" : '\([0-9][0-9]*\)$'`
+    d=`expr "$arg" : '\([5-9]\.[0-9]\.[0-9]\{,2\}-[0-9]\{,2\}*\)$'`
+    v=`expr "$arg" : '\([0-9]\{1,\}\)$'`
     if [ "$d" ]; then
 	ds="$ds $d"
     elif [ "$v" ]; then
@@ -32,35 +43,37 @@ do
 	exit 1
     fi
 done
+
 #
 #   Check Debian version
 #
 for v in $vs
 do
-    if [ $v != 8 -a -f debian/$v/name ]; then
-	test "$DebNum" && echo "$Prg: discarding previously given Debian-version $DebNum (`cat debian/$DebNum/name`)" >&2
+    if [ $v != 8 -a -f $DebTop/$v/name ]; then
+	test "$DebNum" && echo "$Prg: discarding previously given Debian-version $DebNum (`cat $DebTop/$DebNum/name`)" >&2
 	DebNum="$v"
     else
 	echo "$Prg: unsupported Debian version \"$v\"" >&2
 	echo "Supported Debian versions (default $DefDeb):" >&2
-	ls debian | sort -n | grep -v '^8$' | while read v; do test -f debian/$v/name && printf "    %2d (`cat debian/$v/name`)\n" $v; done >&2
+	ls $DebTop | sort -n | grep -v '^8$' | while read v; do test -f $DebTop/$v/name && printf "    %2d (`cat $DebTop/$v/name`)\n" $v; done >&2
 	exit 1
     fi
 done
 test "$DebNum" || DebNum=$DefDeb
-DebVer="`cat debian/$DebNum/name`"
-DebDir=debian/$DebNum
+DebVer="`cat $DebTop/$DebNum/name`"
+DebDir=$DebTop/$DebNum
 
 if [ -f $DebDir/Dockervars.sh ]; then
     eval `sed -n 's/^TESTS_REQ=/MULTI_REQ=/p' $DebDir/Dockervars.sh`
 else
-    echo "$Prg: missing $DebDir/Dockervars.sh" >&2
+    echo "$Prg: missing debian/$DebNum/Dockervars.sh" >&2
     exit 1
 fi
 DistDir=$DebDir/dist
 MultDir=$DebDir/multi
 Logs=$MultDir/logs
 Pkgs=$MultDir/pkgs
+
 #
 #   Check PHP-dists
 #
@@ -81,7 +94,7 @@ test -d $Pkgs && rm -f $Pkgs/*.deb || mkdir -p $Pkgs
 if [ "$ds" ]; then
     for d in $ds
     do
-	eval `echo "$d" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]+)-([0-9]+)$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
+	eval `echo "$d" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]{,2})-([0-9]{,2})$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
 	if DistOK $DistDir/$d $Maj $Min; then
 	    ln $DistDir/$d/$Base-$Maj.$Min-cli_${d}_$Arch.deb $Pkgs
 	    ln $DistDir/$d/$Base-$Maj.$Min-fpm_${d}_$Arch.deb $Pkgs
@@ -90,21 +103,22 @@ if [ "$ds" ]; then
 	    w=$MultDir/www/$h
 	    test -d $w || mkdir -p $w
 	    test -f $w/index.php || echo "<?php header('Location: info.php'); ?>" >$w/index.php
-	    cp -p php/info.php $w
+	    cp -p $PhpTop/run/info.php $w
+	    cp -p ${MulTop}run/run $MultDir
 	    nd=`expr $nd + 1`
 	else
-	    echo "$Prg: $d does not contain the necessary $Base cli and fpm packages" >&2
+	    echo "$Prg: debian/$DebNum/dist/$d does not contain the necessary $Base cli and fpm packages" >&2
 	    exit 1
 	fi
     done
 fi
 if [ $nd -eq 0 ]; then
-    echo "Usage: $Dir/$Prg <PHP-dist-dir> [<PHP-dist-dir> ...] [<Debian-version>]" >&2
+    echo "Usage: $Prg <PHP-dist-dir> [<PHP-dist-dir> ...] [<Debian-version>]" >&2
     echo "Available dists for Debian version $DebNum ($DebVer):" >&2
     Sep=''
     for dir in $DistDir/[5-9].[0-9].[0-9]*-[0-9]*
     do
-	eval `basename $dir | sed -nr 's/^([5-9])\.([0-9])\.([0-9]+)-([0-9]+)$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
+	eval `basename $dir | sed -nr 's/^([5-9])\.([0-9])\.([0-9]{,2})-([0-9]{,2})$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
 	if DistOK $dir $Maj $Min; then
 	    Dists="$Dists$Sep`basename $dir`"
 	    Sep="$LF"
@@ -145,15 +159,21 @@ else
     #
     WaitPkg=`ls $DistDir/tools/epi-tools-waitpid_*_amd64.deb 2>/dev/null`
     if [ -z "$WaitPkg" ]; then
-	tools/mk.sh
+	$TlsTop/bake $DebNum
 	WaitPkg=`ls $DistDir/tools/epi-tools-waitpid_*_amd64.deb 2>/dev/null`
 	if [ -z "$WaitPkg" ]; then
-	    echo "Cannot build the waitpid package, needed to build the '$MULTI_IMG' image" >&2
+	    echo "$Prg: cannot build the waitpid package, needed to build the '$MULTI_IMG' image" >&2
 	    exit 1
 	fi
     fi
+    cp -p $WaitPkg ${MulTop}run
+    Pkg=`basename $WaitPkg`
+    MULCOPY="COPY ${MulTop}run/start $MULTI_TOP/start
+COPY ${MulTop}run/$Pkg /tmp
+RUN dpkg -i /tmp/$Pkg; rm -v /tmp/$Pkg"
     #   Variables come in order of their appearance in Dockerfile-multi.in
-    DEBVER="$DebVer" MULTI_TOP="$MULTI_TOP" MULTI_REQ="$MULTI_REQ" WAITPKG="$WaitPkg" envsubst '$DEBVER $MULTI_TOP $MULTI_REQ $WAITPKG' <docker/Dockerfile-multi.in | tee $Logs/Dockerfile-multi | docker build -f - -t $MULTI_IMG . >$Logs/docker-build.out 2>&1
+    DEBVER="$DebVer" MULTI_TOP="$MULTI_TOP" MULTI_REQ="$MULTI_REQ" MULCOPY="$MULCOPY" envsubst '$DEBVER $MULTI_TOP $MULTI_REQ $MULCOPY' <${MulTop}Dockerfile.in | tee $Logs/Dockerfile-multi | docker build -f - -t $MULTI_IMG . >$Logs/docker-build.out 2>&1
+    rm -f ${MulTop}run/epi-tools-waitpid_*.deb
 fi
 #
 #   Run container
@@ -161,9 +181,9 @@ fi
 test "$HOSTFMT" && RunEnv=' -e HOSTFMT'
 RunCmd()
 {
-    echo "docker run $1$RunEnv -p 80:80 -v `pwd`/$MultDir:$MULTI_TOP/work --name $MULTI_NAME --rm $MULTI_IMG"
+    echo "docker run $1$RunEnv -p 80:80 -v `realpath $PWD/$MultDir`:$MULTI_TOP/work --name $MULTI_NAME --rm $MULTI_IMG"
 }
-if [ -f .norun ]; then
+if [ -f ${TopDir}.norun ]; then
     echo "Use:\n    `RunCmd -ti` bash\nto run the container"
 else
     echo "Running the '$MULTI_NAME' container in background mode:\n    `RunCmd -d`"
diff --git a/php/bake b/php/bake
--- a/php/bake
+++ b/php/bake
@@ -2,19 +2,31 @@
 #
 #	Make PHP packages for a given set of PHP and Debian versions
 #
-#	Usage:	./mk.sh <PHP-version> [<Debian-version>]
+#	Usage:	[php|.]/bake <PHP-version> [<Debian-version>]
 #
 #	PHP-version is checked to be available in PHP sources on $PHPSITE
-#	Supported PHP versions are 5.2, 5.6, 7.1+ on jessie, 5.6 and 7.1+ on later Debian
+#	Supported PHP versions are defined in debian/<Debian-version>/mkre
 #	Debian-version is checked to be supported and defaults to latest version
 #
 PHPSITE='fr.php.net'
 PHPARCH="museum.php.net/php5"
 PECLGET="pecl.php.net/get"
 
-#
-Prg=`basename $0`
+Prg=php/`basename $0`
 Dir=`dirname $0`
+IniPwd=$PWD
+TopDir=../
+DebTop=${TopDir}debian
+PhpTop=
+PhpGit=php/
+
+Path() { realpath --relative-to=$IniPwd $1; }
+test "$Dir" || Dir=`dirname \`realpath $0\``
+expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
+test "$Dir" = '.' || cd "$Dir"
+#   Script's CWD is where it is located, but all messages assume PWD is top-level
+test -d $DebTop || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }
+
 #
 # Get existing PHP 5.x and 7.x versions
 #
@@ -22,7 +34,7 @@ Versions="`curl -sSL "http://$PHPSITE/ChangeLog-5.php" "http://$PHPSITE/ChangeLo
 if [ -z "$Versions" ]; then
     echo "$Prg: unable to fetch the latest lists of PHP versions from \"$PHPSITE\"" >&2
     echo "$Prg: using instead the list of versions already known" >&2
-    Versions="`ls -d php/[5-9]/[5-9].* | sed 's;^php/./;;' | sort -nr -t. -k 1,1 -k 2,2 -k 3,3`"
+    Versions="`ls -d $PhpTop[5-9]/[5-9].* | sed "s;^$PhpTop./;;" | sort -nr -t. -k 1,1 -k 2,2 -k 3,3`"
     if [ -z "$Versions" ]; then
 	echo "$Prg: empty list of known PHP versions ??" >&2
 	exit 1
@@ -62,18 +74,15 @@ SupDeb()
     local v
 
     echo "Supported Debian versions (default $DebNum):" >&2
-    ls debian | sort -n | while read v; do test -f debian/$v/name && printf "    %2d (`cat debian/$v/name`)\n" $v; done >&2
+    ls $DebTop | sort -n | while read v; do test -f $DebTop/$v/name && printf "    %2d (`cat $DebTop/$v/name`)\n" $v; done >&2
 }
 
 #
 #   Check usage
 #
-test "$Dir" = '.' || cd "$Dir"
-test -d debian || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }
-test -d docker || { echo "$Prg: missing 'docker' directory." >&2; exit 1; }
-DebNum=`ls debian | sort -n | tail -1`	# Default = latest
+DebNum=`ls $DebTop | sort -n | tail -1`	# Default = latest
 if [ $# -ne 1 -a $# -ne 2 ]; then
-    echo "Usage: $Dir/$Prg <PHP-version> [ <Debian-version> ]" >&2
+    echo "Usage: $Prg <PHP-version> [ <Debian-version> ]" >&2
     SupPhp supported
     SupDeb
     exit 1
@@ -90,7 +99,7 @@ fi
 eval "$split"
 if echo "$Versions" | grep "^$Maj\.$Min\.$Rel$" >/dev/null; then
     PhpVer="$1"
-    PhpDir=php/$Maj/$PhpVer
+    PhpDir=$PhpTop$Maj/$PhpVer
 else
     echo "$Prg: unknown PHP version \"$1\"" >&2
     SupPhp
@@ -101,7 +110,7 @@ fi
 #   Check Debian version
 #
 if [ "$2" ]; then
-    if [ -f debian/$2/name ]; then
+    if [ -f $DebTop/$2/name ]; then
 	DebNum="$2"
     else
 	echo "$Prg: unsupported Debian version \"$2\"" >&2
@@ -109,8 +118,8 @@ if [ "$2" ]; then
 	exit 1
     fi
 fi
-DebVer="`cat debian/$DebNum/name`"
-DebDir=debian/$DebNum
+DebVer="`cat $DebTop/$DebNum/name`"
+DebDir=$DebTop/$DebNum
 #echo "DebVer=$DebVer PhpVer=$PhpVer Maj=$Maj Min=$Min Rel=$Rel"
 
 #
@@ -139,7 +148,7 @@ if [ ! -s $PhpSrc ]; then
 	dl=y
     else
 	echo "Failed to download $Tbz from known URLs" >&2
-	echo "Put it manually as $PhpSrc and run $Dir/$Prg again" >&2
+	echo "Put it manually as $PhpSrc and run $Prg again" >&2
 	rm -f $PhpSrc
 	test "$mk" && find $PhpDir -type d -empty -delete
 	exit 1
@@ -168,11 +177,11 @@ TESTS_TOP=/opt/php-mk
 if [ -f $DebDir/Dockervars.sh ]; then
     . $DebDir/Dockervars.sh
 else
-    echo "$Prg: missing $DebDir/Dockervars.sh" >&2
+    echo "$Prg: missing debian/$DebNum/Dockervars.sh" >&2
     exit 1
 fi
-if [ -f php/$Maj/Dockervars.sh ]; then
-    . php/$Maj/Dockervars.sh
+if [ -f $PhpTop$Maj/Dockervars.sh ]; then
+    . $PhpTop$Maj/Dockervars.sh	# NOTE: initializes BLDCOPY and possibly TSTCOPY
 else
     echo "$Prg: missing php/$Maj/Dockervars.sh" >&2
     exit 1
@@ -182,7 +191,7 @@ fi
 #   Determine build number and build date
 #
 Num=$PhpDir/BUILD_NUM
-Cmt="`git log -n1 --format=%H -- $Num 2>/dev/null`"
+Cmt="`git log -n1 --format=%H -- $PhpGit$Num 2>/dev/null`"
 if [ "$Cmt" ]; then
     Log=`git show $Cmt:$Num`
     if [ -f $Num ]; then	# If $Num exists and is $Log, set it's mtime to $Cmt's
@@ -199,7 +208,7 @@ test -d $Dist || mkdir -p $Dist
 touch -r $Num $Dist/.date	# For package dates in changelog.Debian
 
 echo "Making PHP $PhpVer-$Bld packages for Debian $DebVer..."
-echo "Logs will be in $Dist/.logs/"
+echo "Logs will be in debian/$DebNum/dist/$PhpVer-$Bld/.logs/"
 test -d $Dist/.logs && rm -f $Dist/.logs/*.out || mkdir $Dist/.logs
 
 #
@@ -210,10 +219,14 @@ BUILD_BASE=epi-build-php
 BUILD_IMG=$BUILD_BASE:$Tag	# Keep all build images separate
 BUILD_NAME=epi_build_php	# Only one build container at a time
 
-test -f .debug && BLDCOPY="$BLDCOPY
-COPY .debug $BUILD_TOP"
-test -f php/.notest && BLDCOPY="$BLDCOPY
-COPY php/.notest $BUILD_TOP"
+BLDCOPY="$BLDCOPY
+COPY $PhpSrc $BUILD_TOP/files
+COPY ${PhpTop}pkgs $BUILD_TOP/pkgs
+COPY ${PhpTop}run/build $BUILD_TOP"
+test -f ${TopDir}.debug && BLDCOPY="$BLDCOPY
+RUN >$BUILD_TOP/.debug"
+test -f ${PhpTop}.notest && BLDCOPY="$BLDCOPY
+RUN >$BUILD_TOP/.notest"
 
 if docker ps | grep $BUILD_NAME >/dev/null; then
     echo "Stopping the running '$BUILD_NAME' container..."
@@ -236,10 +249,10 @@ echo "Building the '$BUILD_IMG' image..."
 User=`id -un`
 AddUser="groupadd -g `id -g` `id -gn`; useradd -u `id -u` -g `id -g` $User"
 #   Variables come in order of their appearance in Dockerfile-build.in
-DEBVER="$DebVer" CLI_DEPS="$CLI_DEPS" BUILD_NUM="$Bld" USER="$User" BUILD_TOP="$BUILD_TOP" PHPVER="$PhpVer" ADDUSER="$AddUser" BUILD_REQ="$BUILD_REQ" PHPSRC="$PhpSrc" BLDCOPY="$BLDCOPY" envsubst '$DEBVER $CLI_DEPS $BUILD_NUM $USER $BUILD_TOP $PHPVER $ADDUSER $BUILD_REQ $PHPSRC $BLDCOPY' <docker/Dockerfile-build.in | tee $Dist/.logs/Dockerfile-build | docker build -f - -t $BUILD_IMG . >$Dist/.logs/docker-build.out 2>&1
+DEBVER="$DebVer" CLI_DEPS="$CLI_DEPS" BUILD_NUM="$Bld" USER="$User" BUILD_TOP="$BUILD_TOP" ADDUSER="$AddUser" BUILD_REQ="$BUILD_REQ" BLDCOPY="$BLDCOPY" envsubst '$DEBVER $CLI_DEPS $BUILD_NUM $USER $BUILD_TOP $ADDUSER $BUILD_REQ $BLDCOPY' <${PhpTop}Dockerfile-build.in | tee $Dist/.logs/Dockerfile-build | docker build -f - -t $BUILD_IMG . >$Dist/.logs/docker-build.out 2>&1
 
-Cmd="docker run -ti -v $PWD/$Dist:$BUILD_TOP/dist --name $BUILD_NAME --rm $BUILD_IMG"
-if [ -f .norun ]; then
+Cmd="docker run -ti -v `realpath $PWD/$Dist`:$BUILD_TOP/dist --name $BUILD_NAME --rm $BUILD_IMG"
+if [ -f ${TopDir}.norun ]; then
     echo "Use:\n    $Cmd bash\nto run the build container"
 else
     echo "Running the '$BUILD_NAME' container:\n    $Cmd"
@@ -253,6 +266,10 @@ echo "------------------------------------------------"
 TESTS_BASE=epi-tests-php
 TESTS_IMG=$TESTS_BASE:$Tag	# Keep all tests images separate
 TESTS_NAME=epi_tests_php	# Only one tests container at a time
+
+TSTCOPY="$TSTCOPY
+COPY ${PhpTop}run/info.php /var/www/html
+COPY ${PhpTop}run/tests $TESTS_TOP"
 
 if docker ps | grep $TESTS_NAME >/dev/null; then
     echo "Stopping the running '$TESTS_NAME' container..."
@@ -273,10 +290,10 @@ fi
 
 echo "Building the '$TESTS_IMG' image..."
 #   Variables come in order of their appearance in Dockerfile-tests.in
-DEBVER="$DebVer" TESTS_TOP="$TESTS_TOP" TESTS_REQ="$TESTS_REQ" TSTCOPY="$TSTCOPY" envsubst '$DEBVER $TESTS_TOP $TESTS_REQ $TSTCOPY' <docker/Dockerfile-tests.in | tee $Dist/.logs/Dockerfile-tests | docker build -f - -t $TESTS_IMG . >$Dist/.logs/docker-tests.out 2>&1
+DEBVER="$DebVer" TESTS_TOP="$TESTS_TOP" TESTS_REQ="$TESTS_REQ" TSTCOPY="$TSTCOPY" envsubst '$DEBVER $TESTS_TOP $TESTS_REQ $TSTCOPY' <${PhpTop}Dockerfile-tests.in | tee $Dist/.logs/Dockerfile-tests | docker build -f - -t $TESTS_IMG . >$Dist/.logs/docker-tests.out 2>&1
 
-Cmd="docker run -ti -v $PWD/$Dist:$TESTS_TOP/dist --name $TESTS_NAME --rm $TESTS_IMG"
-if [ -f .norun ]; then
+Cmd="docker run -ti -v `realpath $PWD/$Dist`:$TESTS_TOP/dist --name $TESTS_NAME --rm $TESTS_IMG"
+if [ -f ${TopDir}.norun ]; then
     echo "Use:\n    $Cmd bash\nto run the tests container"
 else
     echo "Running the '$TESTS_NAME' container:\n    $Cmd"
diff --git a/php/run/build b/php/run/build
--- a/php/run/build
+++ b/php/run/build
@@ -5,17 +5,27 @@
 #
 Prg=`basename $0`
 Bld=`dirname $0`
-Ver="$1"
-SupVer="5.2 5.6 7.0 7.1 7.2"			# UPDATE THIS on new version
+test -d $Bld/files -a -d $Bld/pkgs -a -d $Bld/dist || { "$0: cannot find 'files', 'pkgs' and 'dist' directories"; exit 1; }
+# Get version of latest PHP source
+Ver=`expr "\`ls $Bld/files/php-*.tar.bz2 2>/dev/null\`" : '.*/php-\([0-9\.]*\).tar.bz2'`
+if [ "$Ver" ]; then
+    echo "Found source of PHP $Ver in $Bld/files/"
+else
+    echo "$0: cannot find $Bld/files/php-<PHP-version>.tar.bz2"
+    exit 1
+fi
+SupVer="5.2 5.6 7.0 7.1 7.2"			# UPDATE THIS on new PHP version
+
 Logs="$Bld/dist/.logs"				# Directory for log files
 Pkgs="$Bld/dist/.pkgs"				# List of packages built
 Debug="$Bld/dist/.debug"			# Directory for debug files
-Maj=`echo $Ver | awk -F. '{print $1}'`
-MajMin=`echo $Ver | awk -F. '{print $1 "." $2}'`
 if [ -f $Bld/.debug -o "$2" = 'debug' ]; then
     Dbg=y					# Debug option
     test -d $Debug || su -c "mkdir $Debug" $USER
 fi
+Maj=`echo $Ver | awk -F. '{print $1}'`
+MajMin=`echo $Ver | awk -F. '{print $1 "." $2}'`
+echo " $SupVer " | grep " $MajMin " >/dev/null || echo "NOTICE: PHP version $MajMin is unsupported. Update SupVer= in $0 ?"
 
 set -e	# Stop on errors
 
@@ -31,12 +41,15 @@ mkdir /usr/src/php-$Ver; chown $USER:`id -gn $USER` /usr/src/php-$Ver
 su -c "tar xf $Bld/files/php-$Ver.tar.bz2 -C /usr/src" $USER
 mv /usr/src/php-$Ver /usr/src/php
 
-cd /usr/src/php
+cd /usr/src/php		# All relative paths are to here: do NOT change it!
 PhpAPI=`sed -n 's/ *#define ZEND_MODULE_API_NO //p' Zend/zend_modules.h`
 
 ConfigHelp=$Logs/config-help.out
 ./configure --help >$ConfigHelp
-for Opt in '--with-mysql' '--with-mcrypt' '--with-ttf' '--enable-gd-native-ttf' '--enable-fpm'
+#
+#   Handle options not present in every PHP version
+#
+for Opt in --with-mysql --with-mcrypt --with-ttf --enable-gd-native-ttf --enable-fpm
 do
     case "$Opt" in
 	--with-*)   Sep='[ =[]';;
@@ -54,7 +67,9 @@ fi
 echo "$ExtOpts" | grep -- '--enable-fpm ' >/dev/null || >`ls -d $Bld/pkgs/*-fpm`/skip
 # Skip *-mysql package generation if --with-mysql known
 echo "$ExtOpts" | grep -- '--with-mysql ' >/dev/null && >`ls -d $Bld/pkgs/*-mysql`/skip
-
+#
+#   Handle build-time hooks (mostly for PHP extensions)
+#
 if [ -d $Bld/hooks ]; then
     for hook in $Bld/hooks/*
     do
@@ -202,7 +217,7 @@ Phar='install-pear-nozlib.phar'
 for dir in $Bld/pkgs/*
 do
     PkgDir=`basename $dir`
-    Pkg=`expr "$PkgDir" : '[0-9][0-9]-\(.*\)'`
+    Pkg=`expr "$PkgDir" : '[0-9]\{2\}-\(.*\)'`
     Top=$dir/top
     if [ "$Pkg" = 'pear' ]; then
 	Name="$Base-$Pkg"
diff --git a/tools/bake b/tools/bake
--- a/tools/bake
+++ b/tools/bake
@@ -2,13 +2,21 @@
 #
 #	Build packages for tools
 #
-#	Usage:	./mk.sh [<Debian-version>]
-#		tools/mk.sh [<Debian-version>]
+#	Usage:	[tools|.]/bake [<Debian-version>]
 #
-Prg=`basename $0`
+Prg=tools/`basename $0`
 Dir=`dirname $0`
-DebTop=../debian
-Docker=../docker
+IniPwd=$PWD
+TopDir=../
+DebTop=${TopDir}debian
+TlsTop=
+
+Path() { realpath --relative-to=$IniPwd $1; }
+test "$Dir" || Dir=`dirname \`realpath $0\``
+expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
+test "$Dir" = '.' || cd "$Dir"
+#   Script's CWD is where it is located, but all messages assume PWD is top-level
+test -d $DebTop || { echo "$Prg: missing 'debian' directory." >&2; exit 1; }
 
 SupDeb()
 {
@@ -21,12 +29,9 @@ SupDeb()
 #
 #   Check usage
 #
-test "$Dir" = '.' || cd "$Dir"
-test -d $DebTop || { echo "$Dir/$Prg: missing '$DebTop' directory." >&2; exit 1; }
-test -d $Docker || { echo "$Dir/$Prg: missing '$Docker' directory." >&2; exit 1; }
 DebNum=`ls $DebTop | sort -n | tail -1`	# Default = latest
 if [ $# -gt 1 ]; then
-    echo "Usage: $Dir/$Prg [ <Debian-version> ]" >&2
+    echo "Usage: $Prg [ <Debian-version> ]" >&2
     SupDeb
     exit 1
 fi
@@ -57,6 +62,11 @@ TOOLS_NAME=epi_tools
 date '+===== %Y-%m-%d %H:%M:%S %Z =================='
 Now=`date '+%s'`
 
+TLSCOPY="COPY ${TlsTop}pkgs $TOOLS_TOP/pkgs
+COPY ${TlsTop}run/build $TOOLS_TOP/build"
+test -f ${TopDir}.debug && TLSCOPY="$TLSCOPY
+RUN >$TOOLS_TOP/.debug"
+
 if docker ps | grep $TOOLS_NAME >/dev/null; then
     echo "Stopping the running '$TOOLS_NAME' container..."
     docker stop -t 5 $TOOLS_NAME >/dev/null
@@ -76,14 +86,14 @@ fi
 
 test -d $Logs || mkdir -p $Logs
 echo "Building the '$TOOLS_IMG' image..."
-#   Variables come in order of their appearance in Dockerfile-tools.in
-DEBVER="$DebVer" TOOLS_TOP="$TOOLS_TOP" envsubst '$DEBVER $TOOLS_TOP' <../docker/Dockerfile-tools.in | tee $Logs/Dockerfile | docker build -f - -t $TOOLS_IMG . >$Logs/docker.out 2>&1
+#   Variables come in order of their appearance in Dockerfile.in
+DEBVER="$DebVer" TOOLS_TOP="$TOOLS_TOP" TLSCOPY="$TLSCOPY" envsubst '$DEBVER $TOOLS_TOP $TLSCOPY' <${TlsTop}Dockerfile.in | tee $Logs/Dockerfile | docker build -f - -t $TOOLS_IMG . >$Logs/docker.out 2>&1
 
 #
 #   Run the container
 #
 Cmd="docker run -ti -v `realpath $PWD/$Tools`:$TOOLS_TOP/dist --name $TOOLS_NAME --rm $TOOLS_IMG"
-if [ -f ../.norun ]; then
+if [ -f ${TopDir}.norun ]; then
     echo "Use:\n    $Cmd bash\nto run the tools container"
 else
     echo "Running the '$TOOLS_NAME' container:\n    $Cmd"
