Add cleanup of PEAR 1.9 .registry/.channels files (PHP 5.2) Add OpenSSL patch for PHP 5.6 on stretch (from zettasystem.com) Add top-level .debug file handling to trigger $Dbg in php/build Configure options are now checked from the output of config --help Add special handling of --enable-phpdbg -> --disable-phpdbg Add mandatory column to pkgs/01-cli/moves to allow for optional files Update README.md, PLANNING.md and TODO_NEXT.md

diff --git a/pkgs/01-cli/install b/pkgs/01-cli/install
--- a/pkgs/01-cli/install
+++ b/pkgs/01-cli/install
@@ -2,8 +2,12 @@
 #
 #	01-cli/install - Install php-cli files to $Top
 #
-sed -i "s;install-pear-nozlib.phar -d;install-pear-nozlib.phar -m /$PearDir -D /$DocDir/$Name -M /$ManDir -d;" Makefile
-mkdir -p $Top/$PearDir
+Phar='install-pear-nozlib.phar'
+Pear=$Top/$PearDir
+if grep metadata_dir pear/$Phar >/dev/null; then
+    sed -i "s;$Phar -d;$Phar -m /$PearDir -D /$DocDir/$Name -M /$ManDir -d;" Makefile
+fi
+mkdir -p $Pear
 # Skip install-sapi install-build install-headers install-pdo-headers
 for tgt in install-cli install-binaries install-programs install-modules install-pear install-pharcmd
 do
@@ -12,7 +16,7 @@ done
 test "$Dbg" && echo "Tgts=\"$Tgts\""
 INSTALL_ROOT=$Top PHP_PEAR_SYSCONF_DIR=etc/pear make$Tgts >$Logs/make-install_$Pkg.out 2>&1
 
-while read d f p
+while read d f p m	# Dir File Pkg Mandatory
 do
     test -f $Bld/pkgs/$p/skip && continue
     File=`cd $Top; find $d -type f -name $f`
@@ -22,7 +26,7 @@ do
 	Log=$Logs/make-install_$p.out
 	test -f $Log || echo "Installing $p package" >$Log
 	mv -v $Top/$File $Ext >>$Log 2>&1
-    else
+    elif [ "$m" ]; then
 	echo "\aERROR: no File found in $Top for d=$d f=$f (p=$p)"
 	echo "Directory $d contains:"
 	(cd $Top; find $d -type f)
@@ -36,8 +40,21 @@ else
     echo "\aERROR: no directory pear/man in `pwd`"
 fi
 
-test -d $Top/$VarDir && find $Top/$VarDir -depth -type d | xargs -r rmdir -v >$Logs/rmed_$Pkg.out
-rm -vf $Top/.depdb* >>$Logs/rmed_$Pkg.out
+>$Logs/rmed_$Pkg.out
+
+#   Cleanup PEAR (mostly 1.9.1) junk
+rm -vf $Top/.filemap $Top/.depdb* $Top/.lock $Pear/.depdb* $Pear/.lock >>$Logs/rmed_$Pkg.out
+for d in .channels .registry; do
+    test -d $Top/$d || continue
+    (cd $Top; find $d -type f | while read f; do
+	test -f $Pear/$f && cmp $Top/$f $Pear/$f >/dev/null && rm -v $Top/$f
+    done)
+    find $Top/$d -depth -type d | xargs rmdir -v
+done >>$Logs/rmed_$Pkg.out
+rmdir -v $Pear/.registry/.channel.* >>$Logs/rmed_$Pkg.out
+
+test -d $Top/$VarDir && find $Top/$VarDir -depth -type d | xargs -r rmdir -v >>$Logs/rmed_$Pkg.out
+
 file $Top/usr/bin/* | sed -n 's/^\([^:]*\): *ELF .*$/\1/p' | xargs -r strip -v >$Logs/striped_$Pkg.out
 find $Top -name '*.so' | xargs -r strip -v >>$Logs/striped_$Pkg.out
 find $Top -name '*.so' | xargs -r chmod -x
