Put 'multi' Port and Domain variables in a separate 'srvconf' file:   - change 'multi/bake' to create this 'srvconf' file at build time   - change 'multi/run/start' and 'multi/run/run' to use it Exit 'multi/run/run' on 'docker run' failures Update README.md (mostly autonomous container use for 'multi')

diff --git a/multi/run/run b/multi/run/run
--- a/multi/run/run
+++ b/multi/run/run
@@ -6,19 +6,26 @@ Prg=`basename $0`
 Dir=`dirname $0`
 IniPwd=$PWD
 DocRoot=`realpath "$1" 2>/dev/null`
-Port='$MULTI_PORT'
 
 Path() { realpath --relative-to=$IniPwd $1; }
 test "$Dir" || Dir=`dirname \`realpath $0\``
 expr "$Dir" : / >/dev/null && Dir=`Path $Dir`
 test "$Dir" = '.' || cd "$Dir"
 Prg=`Path "$Prg"`
+
 test -d pkgs || { echo "$Prg: missing '`Path pkgs`' directory." >&2; exit 1; }
+
+PATH="$PATH:"	# dash wants $PWD in the path for the '.' command
+SrvConf=`Path srvconf`
+test -f srvconf && . srvconf || { echo "$Prg: missing '$SrvConf'" >&2; exit 1; }
+test "$Port" || { echo "$Prg: missing 'Port=...' in $SrvConf"; exit 2; }
+
 if [ "$1" ]; then
     test -d "$DocRoot" || { echo "$Prg: '$1' is not a directory" >&2; exit 1; }
 else
     test -d www && DocRoot="$PWD/www" || { echo "$Prg: missing '`Path www`' directory." >&2; exit 1; }
 fi
+
 test -d logs || mkdir logs
 
 if docker ps | grep $MULTI_NAME >/dev/null; then
@@ -28,7 +35,7 @@ fi
 Opt='-d'	# NOTE: multi/bake expects next line to start with Cmd="
 Cmd="docker run $Opt -p $Port:$Port -v $PWD:$MULTI_TOP/conf -v $DocRoot:$MULTI_TOP/www --name $MULTI_NAME --rm $MULTI_IMG"
 echo "Running the '$MULTI_NAME' container in background mode:\n    $Cmd"
-$Cmd >/dev/null
+$Cmd >/dev/null || { echo "\aFAILED to run the '$MULTI_NAME' container!"; exit 1; }
 
 Sec=0
 while [ $Sec -le 30 ]
diff --git a/multi/run/start b/multi/run/start
--- a/multi/run/start
+++ b/multi/run/start
@@ -7,15 +7,21 @@ Dir=`dirname $0`
 Conf='conf'
 Logs="$Dir/$Conf/logs"
 Pkgs="$Dir/$Conf/pkgs"
+SrvConf="$Dir/$Conf/srvconf"
 WWW="$Dir/www"
 Base='epi-php'
 Arch='amd64'
 PkgDeb="+deb$DEBNUM"
-IpSite="http://ipaddr.free.fr"
+Out="$Logs/docker-run.out"
 Own="$USER:`id -gn $USER`"
+
 mkdir -p $Logs
-test $$ -eq 1 && exec >$Logs/docker-run.out 2>&1
-chown $Own $Logs/docker-run.out
+if [ $$ -eq 1 ]; then
+    exec >$Out 2>&1
+    chown $Own $Out
+else
+    rm -f $Out
+fi
 
 set -e	# Stop on errors
 
@@ -27,6 +33,16 @@ fi
 Dists=`ls $Pkgs | sed -nr "s/$Base-[5-9]\.[0-9]-(cli|fpm|mysql)_([5-9]\.[0-9]\.[0-9]{,2}-[0-9]{,2})\\\\${PkgDeb}_$Arch.deb/\2/p" | sort -u`
 if [ -z "$Dists" ]; then
     echo "$Prg: no valid package name in $Pkgs" >&2
+    exit 1
+fi
+
+if [ -s "$SrvConf" ]; then
+    . $SrvConf
+    test "$Port"   || { echo "$Prg: missing 'Port=...' in $SrvConf";   exit 2; }
+    test "$Domain" || { echo "$Prg: missing 'Domain=...' in $SrvConf"; exit 2; }
+    test "$IpSite" || { echo "$Prg: missing 'IpSite=...' in $SrvConf"; exit 2; }
+else
+    echo "$Prg: missing configuration file $SrvConf" >&2
     exit 1
 fi
 
@@ -51,14 +67,16 @@ else
     echo "#
 #   Template for multi-PHP site configuration
 #
-#	%Maj% will be replaced by the PHP major version
-#	%Min% will be replaced by the PHP minor version
+#	%Port% will be replaced by the Port from srvconf
+#	%Maj% will be replaced by the PHP major version from packages
+#	%Min% will be replaced by the PHP minor version from packages
+#	%Domain% will be replaced by the Domain from srvconf
 #
 #   DO NOT change DocumentRoot, it is needed by the container's start script
 #   DO NOT change SetHandler, it is in sync with the PHP-FPM configuration
 #
-<VirtualHost *:$PORT>
-    ServerName php%Maj%%Min%.$DOMAIN
+<VirtualHost *:%Port%>
+    ServerName php%Maj%%Min%.%Domain%
     DocumentRoot $WWW
     <FilesMatch \".+\.ph(ar|p|tml)$\">
         SetHandler \"proxy:unix:/run/php/php%Maj%.%Min%-fpm.sock|fcgi://localhost\"
@@ -84,7 +102,7 @@ do
 	echo "$Prg: cannot find both cli and fpm packages for $dist"
 	continue
     fi
-    SiteConf=`cat $InPath | sed -e "s/%Maj%/$Maj/g" -e "s/%Min%/$Min/g"`
+    SiteConf=`cat $InPath | sed -e "s/%Port%/$Port/g" -e "s/%Maj%/$Maj/g" -e "s/%Min%/$Min/g" -e "s/%Domain%/$Domain/g"`
     Serv=`echo "$SiteConf" | sed -nr 's/^ *ServerName +([^ ]+).*$/\1/p'`
     Hand=`echo "$SiteConf" | sed -nr 's/^ *SetHandler +([^ ]+).*$/\1/p'`
     if echo " $Srvs" | grep " $Serv " >/dev/null; then
@@ -95,11 +113,11 @@ do
     echo "$SiteConf" >/etc/apache2/sites-available/$Serv.conf
     su -c "cp -p /etc/apache2/sites-available/$Serv.conf $Logs" $USER
     a2ensite $Serv.conf >>$Logs/a2.out
-    if [ $PORT -ne 80 ]; then
-	sed -i "/^Listen 80$/s/80/$PORT/" /etc/apache2/ports.conf
-	Port=":$PORT"
+    if [ $Port -ne 80 ]; then
+	sed -i "/^Listen 80$/s/80/$Port/" /etc/apache2/ports.conf
+	Listen=":$Port"
     fi
-    echo "Added site http://$Serv$Port"
+    echo "Added site http://$Serv$Listen"
     echo "    with SetHandler   $Hand"
     Srvs="$Srvs$Serv "
     ns=`expr $ns + 1`
