Add check for lintian failures in tools/run/build and php/run/build

diff --git a/php/run/build b/php/run/build
--- a/php/run/build
+++ b/php/run/build
@@ -410,7 +410,9 @@ do
 
     if [ -f "$deb" ]; then
 	echo "Checking   package '$Pkg': `basename $deb`..."
-	lintian --allow-root $deb >$Logs/lintian_$Pkg.out
+	if ! lintian --allow-root $deb >$Logs/lintian_$Pkg.out; then
+	    test "$ChkPkg" && ChkPkg="$ChkPkg\n$Pkg" || ChkPkg="$Pkg"
+	fi
 	basename $deb >>$Pkgs
 	chown $Own $deb
     else
@@ -429,6 +431,11 @@ done
 chown $Own $Pkgs
 test "$Dbg" && cp -p Makefile $Debug
 
+if [ "$ChkPkg" ]; then
+    echo "FAILED to check the following package(s):"
+    echo "$ChkPkg" | sed 's/^/    /'
+    exit 3
+fi
 if [ "$AsmPkg" ]; then
     echo "FAILED to assemble the following package(s):"
     echo "$AsmPkg" | sed 's/^/    /'
diff --git a/tools/run/build b/tools/run/build
--- a/tools/run/build
+++ b/tools/run/build
@@ -50,7 +50,9 @@ do
 
     if [ -f "$deb" ]; then
 	echo "Checking   package '$Pkg': `basename $deb`..."
-	lintian --allow-root $deb >$Logs/lintian_$Pkg.out
+	if ! lintian --allow-root $deb >$Logs/lintian_$Pkg.out; then
+	    test "$ChkPkg" && ChkPkg="$ChkPkg\n$Pkg" || ChkPkg="$Pkg"
+	fi
 	chown $Own $deb
     else
 	test "$Dbg" && echo "out=\"$out\" deb=\"$deb\""
@@ -65,6 +67,11 @@ do
     fi
     chown $Own $Logs/*_$Pkg.out
 done
+if [ "$ChkPkg" ]; then
+    echo "FAILED to check the following package(s):"
+    echo "$ChkPkg" | sed 's/^/    /'
+    exit 3
+fi
 if [ "$AsmPkg" ]; then
     echo "FAILED to assemble the following package(s):"
     echo "$AsmPkg" | sed 's/^/    /'
