Add new PHP versions 8.1.17 and 8.2.4, with build updates for them

diff --git a/php/run/build b/php/run/build
--- a/php/run/build
+++ b/php/run/build
@@ -25,6 +25,31 @@ Patch()
     fi
 }
 
+NumVer()
+{
+    local IFS fn mul val n
+
+    IFS="${2:-.}" val=0
+    for n in $1
+    do
+	expr "$n" : '[0-9][0-9]*' >/dev/null || { echo "NumVer: '$n' is not a number" >&2; exit 1; }
+	val=$((($val*100)+$n))
+    done
+    echo "$val"
+}
+
+VerCmp()
+{
+    local IFS fn lv op rv
+
+    case "$2" in
+	-l[et]|-g[et]|-eq|-ne)	op=$2;;
+	*) echo "VerCmp: invalid op '$op'" >&2; exit 1;;
+    esac
+    test "$(NumVer $1)" $op "$(NumVer $3)"
+    return $?
+}
+
 #=============================================================================
 #
 # 	Check and setup environment
@@ -45,7 +70,7 @@ if [ -f $Bld/.debug -o "$2" = 'debug' ]; then
 fi
 
 # Get version of latest PHP source
-SupVer="5.2 5.6 7.1 7.4 8.1"		# UPDATE THIS on new PHP version
+SupVer="5.2 5.6 7.1 7.4 8.1 8.2"		# UPDATE THIS on new PHP version
 Ext=.tar.bz2
 Ver=$(expr "$(ls $Bld/files/php-*$Ext 2>/dev/null)" : ".*/php-\([0-9\.]*\)$Ext")
 if [ "$Ver" ]; then
@@ -146,13 +171,14 @@ do
 done
 
 # Skip *-pear package generation if --with-pear unknown
-echo "$ExtOpts" | grep -- '--with-pear=' >/dev/null || >`ls -d $Bld/pkgs/*-pear`/skip
+echo "$ExtOpts" | grep -- '--with-pear=' >/dev/null || >`echo $Bld/pkgs/*-pear`/skip
 # Skip *-fpm package generation if --enable-fpm unknown
-echo "$ExtOpts" | grep -- '--enable-fpm ' >/dev/null || >`ls -d $Bld/pkgs/*-fpm`/skip
+echo "$ExtOpts" | grep -- '--enable-fpm ' >/dev/null || >`echo $Bld/pkgs/*-fpm`/skip
 # Skip *-phpdbg package generation if --enable-phpdbg unknown
-echo "$ExtOpts" | grep -- '--enable-phpdbg ' >/dev/null || >`ls -d $Bld/pkgs/*-phpdbg`/skip
-# Skip *-mysql package generation if --with-mysql known (5.x)
-echo "$ExtOpts" | grep -- '--with-mysql ' >/dev/null && >`ls -d $Bld/pkgs/*-mysql`/skip
+echo "$ExtOpts" | grep -- '--enable-phpdbg ' >/dev/null || >`echo $Bld/pkgs/*-phpdbg`/skip
+# Skip *-mysql package generation if --with-mysql is known before hooks (5.x)
+echo "$ExtOpts" | grep -- '--with-mysql ' >/dev/null && >`echo $Bld/pkgs/*-mysql`/skip
+
 #
 #   Handle build-time hooks (mostly for PHP extensions)
 #
@@ -235,8 +261,8 @@ su -c "EXTENSION_DIR=/usr/lib/php/extensions ./configure \
 	--with-pic \
 	--with-apxs2=/usr/bin/apxs \
 	--with-zlib-dir=/usr \
-	--with-pdo-mysql=/usr \
-	--with-mysqli=/usr/bin/mysql_config \
+	--with-pdo-mysql$PdoMysql \
+	--with-mysqli$MysqlI \
 	--with-bz2 \
 	--with-curl \
 	--with-gettext \
@@ -340,7 +366,7 @@ else
     }
 
     #	Ugly hack for ext/mysqli/tests/mysqli_report.phpt bug
-    test '(' "$DEBNUM" = 10 -o "$DEBNUM" = 11 ')' -a '(' "$MajMin" = '7.4' -o "$MajMin" = '8.1' ')' && rm -v ext/mysqli/tests/mysqli_report.phpt 2>&1 | sed 's/^r/R/'
+    test "$DEBNUM" -ge 10 && VerCmp $MajMin -ge '7.4' && rm -v ext/mysqli/tests/mysqli_report.phpt 2>&1 | sed 's/^r/R/'
 
     date "+%Y-%m-%d %H:%M:%S Testing php-$Ver built for Debian $DEBVER $(cat /etc/debian_version) ..."
     mkOut="$Logs/make-test.out"
