Add PHP and Debian versions to container name, to allow simultaneous builds Update PLANNING.md and README.md about it Check that each docker image exists before running it Do not build PHP 7.0 anymore

diff --git a/php/bake b/php/bake
--- a/php/bake
+++ b/php/bake
@@ -207,7 +207,7 @@ AddUser="groupadd -g `id -g` `id -gn`; useradd -u `id -u` -g `id -g` $User"
 Tag=$DebVer-$PhpVer
 BUILD_BASE=epi-build-php
 BUILD_IMG=$BUILD_BASE:$Tag	# Keep all build images separate
-BUILD_NAME=epi_build_php	# Only one build container at a time
+BUILD_NAME=$BUILD_BASE-${PhpVer}_$DebVer
 
 BLDCOPY="$BLDCOPY
 COPY $PhpSrc $BUILD_TOP/files
@@ -239,12 +239,18 @@ echo "Building the '$BUILD_IMG' image..."
 #   Variables come in order of their appearance in Dockerfile-build.in
 DEBVER="$DebVer" DEBNUM="$DebNum" CLI_DEPS="$CLI_DEPS" BUILD_NUM="$Bld" USER="$User" ADDUSER="$AddUser" BUILD_TOP="$BUILD_TOP" BUILD_REQ="$BUILD_REQ" BLDCOPY="$BLDCOPY" envsubst '$DEBVER $DEBNUM $CLI_DEPS $BUILD_NUM $USER $ADDUSER $BUILD_TOP $BUILD_REQ $BLDCOPY' <${PhpTop}Dockerfile-build.in | tee $Dist/.logs/Dockerfile-build | docker build -f - -t $BUILD_IMG . >$Dist/.logs/docker-build.out 2>&1
 
-Cmd="docker run -ti -v `realpath $PWD/$Dist`:$BUILD_TOP/dist --name $BUILD_NAME --rm $BUILD_IMG"
-if [ -f ${TopDir}.norun ]; then
-    echo "Use:\n    $Cmd bash\nto run the build container"
+if docker images | grep "$BUILD_BASE *$Tag" >/dev/null; then
+    Cmd="docker run -ti -v `realpath $PWD/$Dist`:$BUILD_TOP/dist --name $BUILD_NAME --rm $BUILD_IMG"
+    if [ -f ${TopDir}.norun ]; then
+	echo "Use:\n    $Cmd bash\nto run the build container"
+    else
+	echo "Running the '$BUILD_NAME' container:\n    $Cmd"
+	$Cmd
+    fi
 else
-    echo "Running the '$BUILD_NAME' container:\n    $Cmd"
-    $Cmd
+    echo "FAILED to build the $BUILD_IMG image !"
+    echo "Examine $Dist/.logs/docker-build.out for details."
+    exit 1
 fi
 echo "------------------------------------------------"
 
@@ -253,7 +259,7 @@ echo "------------------------------------------------"
 #
 TESTS_BASE=epi-tests-php
 TESTS_IMG=$TESTS_BASE:$Tag	# Keep all tests images separate
-TESTS_NAME=epi_tests_php	# Only one tests container at a time
+TESTS_NAME=$TESTS_BASE-${PhpVer}_$DebVer
 
 TSTCOPY="$TSTCOPY
 COPY ${PhpTop}run/info.php /var/www/html
@@ -280,12 +286,18 @@ echo "Building the '$TESTS_IMG' image..."
 #   Variables come in order of their appearance in Dockerfile-tests.in
 DEBVER="$DebVer" USER="$User" ADDUSER="$AddUser" TESTS_TOP="$TESTS_TOP" TESTS_REQ="$TESTS_REQ" TSTCOPY="$TSTCOPY" envsubst '$DEBVER $USER $ADDUSER $TESTS_TOP $TESTS_REQ $TSTCOPY' <${PhpTop}Dockerfile-tests.in | tee $Dist/.logs/Dockerfile-tests | docker build -f - -t $TESTS_IMG . >$Dist/.logs/docker-tests.out 2>&1
 
-Cmd="docker run -ti -v `realpath $PWD/$Dist`:$TESTS_TOP/dist --name $TESTS_NAME --rm $TESTS_IMG"
-if [ -f ${TopDir}.norun ]; then
-    echo "Use:\n    $Cmd bash\nto run the tests container"
+if docker images | grep "$TESTS_BASE *$Tag" >/dev/null; then
+    Cmd="docker run -ti -v `realpath $PWD/$Dist`:$TESTS_TOP/dist --name $TESTS_NAME --rm $TESTS_IMG"
+    if [ -f ${TopDir}.norun ]; then
+	echo "Use:\n    $Cmd bash\nto run the tests container"
+    else
+	echo "Running the '$TESTS_NAME' container:\n    $Cmd"
+	$Cmd
+    fi
 else
-    echo "Running the '$TESTS_NAME' container:\n    $Cmd"
-    $Cmd
+    echo "FAILED to build the $TESTS_IMG image !"
+    echo "Examine $Dist/.logs/docker-tests.out for details."
+    exit 1
 fi
 
 #
