Add mysql package (when it exists) to multi.sh packages Restart php-fpm as well as apache2 in mysql package's postinst/postrm Add fake /sbin/runlevel and tweak docker's policy-rc.d to make invoke-rc.d work Simplify mod package's postinst as a consequence Make /etc/init.d/php-fpm status return proper exit codes Re-use the epi-multi-php:... image when it exists. A build needs a docker rmi Add virtual hostname formatting with an optional HOSTFMT environment variable Update README.md, PLANNING.md and TODO_NEXT.md

diff --git a/php/start b/php/start
--- a/php/start
+++ b/php/start
@@ -9,21 +9,29 @@ Logs="$Work/logs"
 Pkgs="$Work/pkgs"
 Base='epi-php'
 Arch='amd64'
-Domain="epiconcept.tld"
+HostFmt="${HOSTFMT:-php%M%m.epiconcept.tld}"
 IpSite="http://ipaddr.free.fr"
 DebNum=`expr \`cat /etc/debian_version\` : '\([0-9]*\)'`
 test $$ -eq 1 && exec >$Logs/docker-run.out 2>&1
+
+set -e	# Stop on errors
 
 if [ ! -d $Pkgs ]; then
     echo "$Prg: directory $Pkgs is missing" >&2
     exit 1
 fi
-set -e
-Dists="`ls $Pkgs | sed -nr "s/$Base-[5-9]\.[0-9]-(cli|fpm)_([5-9]\.[0-9]\.[0-9]+-[0-9]+)_$Arch.deb/\2/p" | sort -u`"
+
+Dists="`ls $Pkgs | sed -nr "s/$Base-[5-9]\.[0-9]-(cli|fpm|mysql)_([5-9]\.[0-9]\.[0-9]+-[0-9]+)_$Arch.deb/\2/p" | sort -u`"
 if [ -z "$Dists" ]; then
     echo "$Prg: no valid package name in $Pkgs" >&2
     exit 1
 fi
+
+if [ ! -e /sbin/runlevel ]; then	# Needed by invoke-rc.d
+    echo "#!/bin/sh\necho \"${PREVLEVEL:-N} ${RUNLEVEL:-5}\"" >/sbin/runlevel
+    chmod +x /sbin/runlevel
+fi
+test -x /usr/sbin/policy-rc.d && grep 'exit 101' /usr/sbin/policy-rc.d >/dev/null && sed -i 's/exit 101/exit 104/' /usr/sbin/policy-rc.d 
 
 sed -i '1iServername localhost' /etc/apache2/sites-available/000-default.conf
 a2enmod proxy_fcgi >$Logs/a2.out
@@ -34,35 +42,37 @@ do
     eval `echo "$dist" | sed -nr 's/^([5-9])\.([0-9])\.([0-9]+)-([0-9]+)$/Maj=\1 Min=\2 Rel=\3 Bld=\4/p'`
     if [ -s $Pkgs/$Base-$Maj.$Min-cli_${dist}_$Arch.deb -a -s $Pkgs/$Base-$Maj.$Min-fpm_${dist}_$Arch.deb ]; then
 	dpkg -i $Pkgs/$Base-$Maj.$Min-cli_${dist}_$Arch.deb $Pkgs/$Base-$Maj.$Min-fpm_${dist}_$Arch.deb >>$Logs/dpkg-i.out
+	test -s $Pkgs/$Base-$Maj.$Min-mysql_${dist}_$Arch.deb && dpkg -i $Pkgs/$Base-$Maj.$Min-mysql_${dist}_$Arch.deb >>$Logs/dpkg-i.out
+	echo "----------------------------------------" >>$Logs/dpkg-i.out
     else
 	echo "$Prg: cannot find both cli and fpm packages for $dist"
 	continue
     fi
     fpm=php$Maj.$Min-fpm
-    www=$Work/www/php$Maj$Min
-    site=php$Maj$Min.$Domain
+    site=`echo "$HostFmt" | sed -e "s/%M/$Maj/g" -e "s/%m/$Min/g"`
+    www=www/`echo $site | awk -F. '{print $1}'`
     echo "<VirtualHost *:80>
     ServerName $site
-    DocumentRoot $www
+    DocumentRoot $Work/$www
     <FilesMatch \".+\.ph(ar|p|tml)$\">
         SetHandler \"proxy:unix:/run/php/$fpm.sock|fcgi://localhost\"
     </FilesMatch>
-    <Directory $www>
+    <Directory $Work/$www>
 	AllowOverride all
 	Require all granted
     </Directory>
 </VirtualHost>" >/etc/apache2/sites-available/$site.conf
     a2ensite $site.conf >>$Logs/a2.out
-    echo "Added site http://$site for host-dir debian/$DebNum/multi/www/php$Maj$Min"
+    echo "Added site http://$site with DocumentRoot $Work/$www"
     ok=y
 done
 IPAddr="`curl -sSL "$IpSite" 2>/dev/null | awk 'NR == 1 {print "IP=" $0} NR==2 { print "NS=" $0}'`"
 if [ "$IPAddr" ]; then
     eval "$IPAddr"
-    echo "Our IP address is $IP ($NS)"
+    echo "Our public IP address is $IP ($NS)"
 fi
 if [ "$ok" ]; then
-    service apache2 start
+    service apache2 restart >>$Logs/a2.out
     test $$ -eq 1 && exec waitpid
 else
     echo "$Prg: no valid site to start" >&2
